  ***   Warning: not enough memory, new PARI stack 8713719808
Traceback (most recent call last):
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/src/bin/sage-eval", line 10, in <module>
    eval(compile(s,'<cmdline>','exec'))
  File "<cmdline>", line 1, in <module>
  File "sage/misc/persist.pyx", line 173, in sage.misc.persist.load (build/cythonized/sage/misc/persist.c:2563)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/repl/load.py", line 272, in load
    exec(preparse_file(f.read()) + "\n", globals)
  File "<string>", line 14, in <module>
  File "sage/misc/persist.pyx", line 173, in sage.misc.persist.load (build/cythonized/sage/misc/persist.c:2563)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/repl/load.py", line 272, in load
    exec(preparse_file(f.read()) + "\n", globals)
  File "<string>", line 7, in <module>
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1019, in attach_spec
    s = self.eval('AttachSpec("%s")' % filename)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/interfaces/magma.py", line 558, in eval
    ans = Expect.eval(self, x, **kwds).replace('\\\n', '')
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1381, in eval
    return '\n'.join([self._eval_line(L, allow_use_file=allow_use_file, **kwds)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1381, in <listcomp>
    return '\n'.join([self._eval_line(L, allow_use_file=allow_use_file, **kwds)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/interfaces/expect.py", line 947, in _eval_line
    self._start()
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/interfaces/magma.py", line 598, in _start
    Expect._start(self)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/interfaces/expect.py", line 492, in _start
    self._expect = SageSpawn(cmd,
  File "sage/interfaces/sagespawn.pyx", line 65, in sage.interfaces.sagespawn.SageSpawn.__init__ (build/cythonized/sage/interfaces/sagespawn.c:1984)
  File "sage/interfaces/sagespawn.pyx", line 66, in sage.interfaces.sagespawn.SageSpawn.__init__ (build/cythonized/sage/interfaces/sagespawn.c:1938)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/pexpect/pty_spawn.py", line 205, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/pexpect/pty_spawn.py", line 303, in _spawn
    self.ptyproc = self._spawnpty(self.args, env=self.env,
  File "sage/interfaces/sagespawn.pyx", line 82, in sage.interfaces.sagespawn.SageSpawn._spawnpty (build/cythonized/sage/interfaces/sagespawn.c:2175)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/ptyprocess/ptyprocess.py", line 220, in spawn
    pid, fd = pty.fork()
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/pty.py", line 98, in fork
    pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
